# Generated by Django 4.1.3 on 2022-12-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ComName", models.TextField()),
                ("Scope1", models.IntegerField()),
                ("Scope2", models.IntegerField()),
                ("Scope3", models.IntegerField()),
                ("Classification", models.TextField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User_Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "UID",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("PassWd", models.CharField(blank=True, max_length=10, null=True)),
                ("Name", models.TextField()),
                ("PhoneNum", models.TextField()),
                ("Email", models.EmailField(max_length=254)),
                ("Mother", models.TextField()),
                ("Company", models.TextField()),
                ("JobPos", models.TextField()),
                ("IdentityNum", models.TextField()),
                ("Authorization", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DepartmentName", models.TextField()),
                ("Scope1", models.IntegerField()),
                ("Scope2", models.IntegerField()),
                ("Scope3", models.IntegerField()),
                ("Classification", models.TextField(blank=True, null=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("depth", models.IntegerField()),
                (
                    "Mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Carbon.company"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adminDepart",
                        to="Carbon.user_employee",
                    ),
                ),
                (
                    "chief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chiefDepart",
                        to="Carbon.user_employee",
                    ),
                ),
                (
                    "upper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Carbon.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adminCom",
                to="Carbon.user_employee",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="chief",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chiefCom",
                to="Carbon.user_employee",
            ),
        ),
        migrations.CreateModel(
            name="Carbon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Content", models.TextField()),
                ("Data", models.FloatField()),
                ("unit", models.TextField()),
                ("CarbonEmission", models.FloatField()),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField()),
                ("location", models.TextField()),
                ("Scope", models.IntegerField()),
                ("Category", models.IntegerField()),
                ("Division", models.TextField(null=True)),
                (
                    "Mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Carbon.company"
                    ),
                ),
                (
                    "chief",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Carbon.user_employee",
                    ),
                ),
                (
                    "upper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Carbon.department",
                    ),
                ),
            ],
        ),
    ]
